// Generated by setup.html on 2026-10-05T23:31:47.722Z
// This file holds YOUR project's key - keep it next to index.html.
window.SUPABASE_URL = "https://xslgbvgefiojbhxbyxpe.supabase.co";
window.SUPABASE_KEY = "sb_publishable_nAz1ZvWTkCyt-topoSJldA_hkBsj-c9";
